server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pet
          uri: http://localhost:8081
          predicates:
            - Path=/pets/** 
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/items/**, /orderItems/**, /customers/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pet
          uri: http://pet:8080
          predicates:
            - Path=/pets/** 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/items/**, /orderItems/**, /customers/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
